appname="FlickBoard"
appver="2.1"
appcode="1"
packagename="github.znzsofficial.flick"
theme="Theme"
welcome_time="0"
debugmode=false
enableExtendedOutputSupport=true
enableDialogLog=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
